### ISSUE TITLE
Agregar página con listado de colaboradores

### ISSUE THREAD

**Issue by eatskolnikov** [Streamelopers/opus-web#33]
Url de colaboradores para el proyecto de API
https://api.github.com/repositories/329980816/contributors 

Url de colaboradores para el proyecto de Web
https://api.github.com/repositories/329978688/contributors

**Comment by JhonasV** [comment]
Me gustaria tomar este issue

**Comment by DannyFeliz** [comment]
Dale @JhonasV

**Comment by JhonasV** [comment]
Se ha abierto un PR para cerrar este issue:
PR #35 

Quedo atento a sus reviews @eatskolnikov  @DannyFeliz

**Comment by DannyFeliz** [comment]
closed #35
