### ISSUE TITLE
Agregar el listado de colaboradores

### ISSUE THREAD

**Issue by eatskolnikov** [Streamelopers/opus-web#46]
Vamos a usar el componente de grid de este template
https://justcamp-next.netlify.app/search-grid

Url de colaboradores para el proyecto de API
https://api.github.com/repositories/329980816/contributors

Url de colaboradores para el proyecto de Web
https://api.github.com/repositories/329978688/contributors

**Comment by JhonasV** [comment]
Me gustaria tomar este issue...

**Comment by Jadhielv** [comment]
@JhonasV Sure, go ahead.

**Comment by eatskolnikov** [comment]
De a 3 items en el grid por fila

![image](https://user-images.githubusercontent.com/1693000/141142304-4541b315-2d87-439e-8eb8-d9ed4ddd92ec.png)

**Comment by JhonasV** [comment]
Se ha creado este PR #51 para cerrar este issue.
